server:
  port: 8761
spring:
  application:
    name: eurka-server-dev
eureka:
  instance:
    hostname: 10.2.101.73
  client:
    registerWithEureka: false #是否将自身注册到eureka
    fetchRegistry: false      #是否抓取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/